SCR_MissionHeaderCampaign {
 World "{98B621609309F790}Worlds/CFP_EdenConflictGamemode.ent"
 m_sName "Everon Reimagined - Conflict Plus"
 m_sAuthor "KosherNaCl & Bradly"
 m_sDescription "The first version of a Conflict Plus"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags SpawnVehicles
 m_eDefaultGameFlags SpawnVehicles
 m_fXpMultiplier 2
 m_iMapMarkerLimitPerPlayer 50
}